/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Castel(props) {
   const { nodes, materials } = useGLTF("/models/snowCastel.glb");

   useEffect(() => {
      const snowMaterialNames = Object.keys(materials).filter((name) =>
         name.toLowerCase().includes("snow")
      );

      Object.values(nodes).forEach((node) => {
         if (node.isMesh && snowMaterialNames.includes(node.material.name)) {
            node.layers.set(1); // 🌟 Put this mesh in bloom layer

            // Optional: Add emissive glow to help bloom
            if (node.material.emissive) {
               node.material.emissive.set("white");
               node.material.emissiveIntensity = 0.0;
            } else {
               node.material.emissive = new THREE.Color("white");
               node.material.emissiveIntensity = 0.0;
            }
         }
      });
   }, [nodes, materials]);

   return (
      <group {...props} dispose={null}>
         <group name="Scene">
            <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.003}>
               <group name="be1eccd4fb914b6b8eac05165472a9f7fbx" rotation={[Math.PI / 2, 0, 0]}>
                  <group name="RootNode">
                     <group
                        name="Camera"
                        position={[-2602.3, 2297.348, 2991.644]}
                        rotation={[0, 0.927, -0.05]}
                        scale={100}
                     >
                        <group name="Object_4" />
                     </group>
                     <group
                        name="Camera001"
                        position={[-4523.928, 2901.941, 9121.189]}
                        rotation={[0, 1.087, -0.071]}
                        scale={161.23}
                     >
                        <group name="Object_12" />
                     </group>
                     <group
                        name="Cobblestone_wall001"
                        position={[0.543, 1981.756, -381.258]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                     >
                        <mesh
                           name="Cobblestone_wall001_4_Bois_0"
                           castShadow
                           receiveShadow
                           geometry={nodes.Cobblestone_wall001_4_Bois_0.geometry}
                           material={materials["4_Bois.002"]}
                        >
                           <mesh
                              name="SnowBall016"
                              castShadow
                              receiveShadow
                              geometry={nodes.SnowBall016.geometry}
                              material={materials["Snow.084"]}
                              position={[9.025, -0.152, 9.939]}
                              rotation={[Math.PI / 2, 0, 0]}
                              scale={3.604}
                           />
                        </mesh>
                     </group>
                     <group
                        name="Cobblestone_wall002"
                        position={[0.543, 1981.756, -381.258]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                     >
                        <mesh
                           name="Cobblestone_wall002_5_Poutres_0"
                           castShadow
                           receiveShadow
                           geometry={nodes.Cobblestone_wall002_5_Poutres_0.geometry}
                           material={materials["5_Poutres.002"]}
                        >
                           <mesh
                              name="SnowBall004"
                              castShadow
                              receiveShadow
                              geometry={nodes.SnowBall004.geometry}
                              material={materials["Snow.072"]}
                              position={[4.587, -0.51, 2.166]}
                              rotation={[Math.PI / 2, 0, 0]}
                              scale={3.604}
                           />
                        </mesh>
                     </group>
                     <group
                        name="Cobblestone_wall009"
                        position={[0.543, 1981.756, -381.258]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                     >
                        <mesh
                           name="Cobblestone_wall009_Cobblestone_0"
                           castShadow
                           receiveShadow
                           geometry={nodes.Cobblestone_wall009_Cobblestone_0.geometry}
                           material={materials["Cobblestone.002"]}
                        >
                           <mesh
                              name="SnowBall006"
                              castShadow
                              receiveShadow
                              geometry={nodes.SnowBall006.geometry}
                              material={materials["Snow.074"]}
                              position={[5.077, 4.285, 14.862]}
                              rotation={[Math.PI / 2, 0, 0]}
                              scale={3.604}
                           />
                        </mesh>
                     </group>
                     <group
                        name="Cobblestone_wall011"
                        position={[0.543, 1981.756, -381.258]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                     >
                        <mesh
                           name="Cobblestone_wall011_Cobblestone_2_0"
                           castShadow
                           receiveShadow
                           geometry={nodes.Cobblestone_wall011_Cobblestone_2_0.geometry}
                           material={materials["Cobblestone_2.002"]}
                        >
                           <mesh
                              name="SnowBall008"
                              castShadow
                              receiveShadow
                              geometry={nodes.SnowBall008.geometry}
                              material={materials["Snow.076"]}
                              position={[-1.979, -0.555, -21.003]}
                              rotation={[Math.PI / 2, 0, 0]}
                              scale={3.604}
                           />
                        </mesh>
                        <mesh
                           name="Cobblestone_wall011_Cobblestone_2_0001"
                           castShadow
                           receiveShadow
                           geometry={nodes.Cobblestone_wall011_Cobblestone_2_0001.geometry}
                           material={materials["Cobblestone_2.002"]}
                        >
                           <mesh
                              name="SnowBall009"
                              castShadow
                              receiveShadow
                              geometry={nodes.SnowBall009.geometry}
                              material={materials["Snow.077"]}
                              position={[-3.245, -2.779, -58.589]}
                              rotation={[Math.PI / 2, 0, 0]}
                              scale={3.604}
                           />
                        </mesh>
                        <mesh
                           name="Cobblestone_wall011_Cobblestone_2_0002"
                           castShadow
                           receiveShadow
                           geometry={nodes.Cobblestone_wall011_Cobblestone_2_0002.geometry}
                           material={materials["Cobblestone_2.002"]}
                        >
                           <mesh
                              name="SnowBall010"
                              castShadow
                              receiveShadow
                              geometry={nodes.SnowBall010.geometry}
                              material={materials["Snow.078"]}
                              position={[-2.025, -0.684, -11.944]}
                              rotation={[Math.PI / 2, 0, 0]}
                              scale={3.604}
                           />
                        </mesh>
                        <mesh
                           name="Cobblestone_wall011_Cobblestone_2_0003"
                           castShadow
                           receiveShadow
                           geometry={nodes.Cobblestone_wall011_Cobblestone_2_0003.geometry}
                           material={materials["Cobblestone_2.002"]}
                        >
                           <mesh
                              name="SnowBall011"
                              castShadow
                              receiveShadow
                              geometry={nodes.SnowBall011.geometry}
                              material={materials["Snow.079"]}
                              position={[0.953, 0.782, -6.931]}
                              rotation={[Math.PI / 2, 0, 0]}
                              scale={3.604}
                           />
                        </mesh>
                        <mesh
                           name="Cobblestone_wall011_Cobblestone_2_0004"
                           castShadow
                           receiveShadow
                           geometry={nodes.Cobblestone_wall011_Cobblestone_2_0004.geometry}
                           material={materials["Cobblestone_2.002"]}
                        >
                           <mesh
                              name="SnowBall012"
                              castShadow
                              receiveShadow
                              geometry={nodes.SnowBall012.geometry}
                              material={materials["Snow.080"]}
                              position={[-0.095, 4.597, 5.626]}
                              rotation={[Math.PI / 2, 0, 0]}
                              scale={3.604}
                           />
                        </mesh>
                     </group>
                     <group
                        name="Cobblestone_wall012"
                        position={[0.543, 1981.756, -381.258]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                     >
                        <mesh
                           name="Cobblestone_wall012_4_Bois_0"
                           castShadow
                           receiveShadow
                           geometry={nodes.Cobblestone_wall012_4_Bois_0.geometry}
                           material={materials["4_Bois.002"]}
                        >
                           <mesh
                              name="SnowBall013"
                              castShadow
                              receiveShadow
                              geometry={nodes.SnowBall013.geometry}
                              material={materials["Snow.081"]}
                              position={[-1.844, 4.073, 6.117]}
                              rotation={[Math.PI / 2, 0, 0]}
                              scale={3.604}
                           />
                        </mesh>
                     </group>
                     <group
                        name="Cobblestone_wall013"
                        position={[0.543, 1981.756, -381.258]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                     >
                        <mesh
                           name="Cobblestone_wall013_5_Poutres_0"
                           castShadow
                           receiveShadow
                           geometry={nodes.Cobblestone_wall013_5_Poutres_0.geometry}
                           material={materials["5_Poutres.002"]}
                        >
                           <mesh
                              name="SnowBall014"
                              castShadow
                              receiveShadow
                              geometry={nodes.SnowBall014.geometry}
                              material={materials["Snow.082"]}
                              position={[11.831, 0.995, 2.591]}
                              rotation={[Math.PI / 2, 0, 0]}
                              scale={3.604}
                           />
                        </mesh>
                     </group>
                     <group
                        name="Cobblestone_wall016"
                        position={[0.543, 1981.756, -381.258]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                     >
                        <mesh
                           name="Cobblestone_wall016_Cobblestone_0"
                           castShadow
                           receiveShadow
                           geometry={nodes.Cobblestone_wall016_Cobblestone_0.geometry}
                           material={materials["Cobblestone.002"]}
                        >
                           <mesh
                              name="SnowBall015"
                              castShadow
                              receiveShadow
                              geometry={nodes.SnowBall015.geometry}
                              material={materials["Snow.083"]}
                              position={[1.01, 0.081, -8.367]}
                              rotation={[Math.PI / 2, 0, 0]}
                              scale={3.604}
                           />
                        </mesh>
                     </group>
                     <group
                        name="Cube001"
                        position={[1014.77, 1328.183, 217.513]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                     >
                        <mesh
                           name="Cube001__0"
                           castShadow
                           receiveShadow
                           geometry={nodes.Cube001__0.geometry}
                           material={materials["Cube.001__0.002"]}
                        >
                           <mesh
                              name="SnowBall002"
                              castShadow
                              receiveShadow
                              geometry={nodes.SnowBall002.geometry}
                              material={materials["Snow.070"]}
                              position={[-0.078, -0.004, 0.14]}
                              rotation={[Math.PI / 2, 0, 0]}
                              scale={3.604}
                           />
                        </mesh>
                     </group>
                     <group
                        name="Cube014"
                        position={[1593.935, 1431.995, -477.65]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                     >
                        <mesh
                           name="Cube014__0"
                           castShadow
                           receiveShadow
                           geometry={nodes.Cube014__0.geometry}
                           material={materials["Cube.001__0.002"]}
                           position={[-2.701, 0, 0]}
                        >
                           <mesh
                              name="SnowBall003"
                              castShadow
                              receiveShadow
                              geometry={nodes.SnowBall003.geometry}
                              material={materials["Snow.071"]}
                              position={[-0.08, 0.009, 0.142]}
                              rotation={[Math.PI / 2, 0, 0]}
                              scale={3.604}
                           />
                        </mesh>
                     </group>
                     <group
                        name="Fougeres"
                        position={[493.935, 1647.019, -672.466]}
                        rotation={[-2.667, -0.946, -1.588]}
                        scale={[104.706, 109.211, 152.554]}
                     >
                        <mesh
                           name="Fougeres_Mat_Fern_0"
                           castShadow
                           receiveShadow
                           geometry={nodes.Fougeres_Mat_Fern_0.geometry}
                           material={materials["Mat_Fern.002"]}
                        >
                           <mesh
                              name="SnowBall001"
                              castShadow
                              receiveShadow
                              geometry={nodes.SnowBall001.geometry}
                              material={materials["Snow.069"]}
                              position={[0.19, -2.004, 0.392]}
                              rotation={[2.157, 0.339, -1.489]}
                              scale={[2.719, 3.355, 3.108]}
                           />
                        </mesh>
                     </group>
                     <group
                        name="Plane001"
                        position={[-289.027, 1067.564, -330.916]}
                        rotation={[0, Math.PI / 2, 0]}
                        scale={100}
                     >
                        <mesh
                           name="Plane001_6_fenetre_0"
                           castShadow
                           receiveShadow
                           geometry={nodes.Plane001_6_fenetre_0.geometry}
                           material={materials["6_fenetre.002"]}
                        >
                           <mesh
                              name="SnowBall007"
                              castShadow
                              receiveShadow
                              geometry={nodes.SnowBall007.geometry}
                              material={materials["Snow.075"]}
                              position={[-1.763, 2.997, 7.521]}
                              rotation={[0, -1.571, 0]}
                              scale={3.604}
                           />
                        </mesh>
                     </group>
                     <group
                        name="Sun"
                        position={[1354.312, 2181.466, 754.482]}
                        rotation={[-3.027, -0.162, 2.179]}
                        scale={100}
                     >
                        <group name="Object_18" rotation={[Math.PI / 2, 0, 0]}>
                           <group name="Object_19" />
                        </group>
                     </group>
                     <group
                        name="Toit"
                        position={[0.543, 1981.756, -381.258]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                     >
                        <mesh
                           name="Toit_Roof_Zinc_0"
                           castShadow
                           receiveShadow
                           geometry={nodes.Toit_Roof_Zinc_0.geometry}
                           material={materials["Roof_Zinc.002"]}
                        >
                           <mesh
                              name="SnowBall005"
                              castShadow
                              receiveShadow
                              geometry={nodes.SnowBall005.geometry}
                              material={materials["Snow.073"]}
                              position={[1.803, 1.632, 5.044]}
                              rotation={[Math.PI / 2, 0, 0]}
                              scale={3.604}
                           />
                        </mesh>
                     </group>
                  </group>
               </group>
            </group>
         </group>
      </group>
   );
}

useGLTF.preload("/models/snowCastel.glb");
